# Generated by Django 2.2.10 on 2021-08-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=12, null=True)),
                ('lemma', models.CharField(blank=True, max_length=30, null=True)),
                ('root', models.CharField(blank=True, max_length=30, null=True)),
                ('polarity', models.IntegerField(default=0)),
                ('meaning', models.BinaryField(null=True)),
                ('is_currency', models.BooleanField(null=True)),
                ('is_punct', models.BooleanField(null=True)),
                ('is_stop', models.BooleanField(null=True)),
                ('is_offensive', models.BooleanField(null=True)),
                ('is_digit', models.BooleanField(null=True)),
            ],
        ),
    ]
